//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Genlife_Assesment.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Policy
    {
        public int ID { get; set; }
        public long PolicyNmber { get; set; }
        public string ClientName { get; set; }
        public string ClientSurname { get; set; }
        public System.DateTime DateJoined { get; set; }
    }
}
